export const COURSES = [
  {
    slug: 'rs-cit',
    title: 'RS-CIT',
    fullName: 'Rajasthan State Certificate in Information Technology',
    description:
      'Government certified computer literacy course. Learn essential computer skills, MS Office, internet usage and digital tools.',
    duration: '3 Months',
    fees: 3600,
    discountedFees: 3200,
    icon: 'RS',
    color: 'from-blue-500 to-cyan-500',
    category: 'Government Certified',
    topics: [
      'Computer Basics',
      'Windows OS',
      'MS Word',
      'MS Excel',
      'MS PowerPoint',
      'Internet & Email',
      'Digital Payments',
      'Cyber Security',
    ],
    roadmap: [
      { week: 'Week 1-2', title: 'Computer Fundamentals', desc: 'Hardware, software, and OS basics' },
      { week: 'Week 3-4', title: 'MS Office Suite', desc: 'Word, Excel, and PowerPoint' },
      { week: 'Week 5-6', title: 'Internet & Email', desc: 'Browsing, Gmail, and online tools' },
      { week: 'Week 7-8', title: 'Digital India Tools', desc: 'DigiLocker, UMANG, and digital payments' },
      { week: 'Week 9-12', title: 'Practice & Exam Prep', desc: 'Mock tests, revision, and certification prep' },
    ],
    badge: 'Govt. Certified',
    popular: false,
  },
  {
    slug: 'web-development',
    title: 'Web Development',
    fullName: 'Full Stack Web Development',
    description:
      'Learn HTML, CSS, JavaScript, React and Node.js to build modern websites and web applications from scratch.',
    duration: '6 Months',
    fees: 15000,
    discountedFees: 12000,
    icon: 'WEB',
    color: 'from-violet-500 to-purple-600',
    category: 'Technical',
    topics: [
      'HTML5 & CSS3',
      'JavaScript ES6+',
      'React.js',
      'Node.js',
      'MongoDB',
      'REST APIs',
      'Git & GitHub',
      'Project Deployment',
    ],
    roadmap: [
      { week: 'Month 1', title: 'HTML & CSS', desc: 'Structure, styling, and responsive design' },
      { week: 'Month 2', title: 'JavaScript', desc: 'Programming basics to advanced JavaScript' },
      { week: 'Month 3', title: 'React.js', desc: 'Components, hooks, and state management' },
      { week: 'Month 4', title: 'Backend (Node.js)', desc: 'Express, APIs, and authentication' },
      { week: 'Month 5', title: 'Database (MongoDB)', desc: 'CRUD, Mongoose, and deployment' },
      { week: 'Month 6', title: 'Projects & Portfolio', desc: 'Three real-world projects' },
    ],
    badge: 'Most Popular',
    popular: true,
  },
  {
    slug: 'digital-marketing',
    title: 'Digital Marketing',
    fullName: 'Complete Digital Marketing',
    description:
      'Master SEO, social media, Google Ads, email marketing and analytics to grow businesses online.',
    duration: '3 Months',
    fees: 8000,
    discountedFees: 6500,
    icon: 'DM',
    color: 'from-orange-500 to-red-500',
    category: 'Marketing',
    topics: [
      'SEO & SEM',
      'Social Media Marketing',
      'Google Ads',
      'Meta Ads',
      'Email Marketing',
      'Content Strategy',
      'Analytics',
      'Canva Design',
    ],
    roadmap: [
      { week: 'Week 1-2', title: 'Digital Marketing Basics', desc: 'Channels, strategy, and marketing mindset' },
      { week: 'Week 3-4', title: 'Social Media Marketing', desc: 'Instagram, Facebook, and LinkedIn' },
      { week: 'Week 5-6', title: 'SEO & Google Tools', desc: 'Search optimization and analytics' },
      { week: 'Week 7-8', title: 'Paid Advertising', desc: 'Google Ads and Meta Ads campaigns' },
      { week: 'Week 9-12', title: 'Real Campaigns & Projects', desc: 'Live campaigns and portfolio building' },
    ],
    badge: 'High Demand',
    popular: false,
  },
  {
    slug: 'graphic-designing',
    title: 'Graphic Designing',
    fullName: 'Professional Graphic Design',
    description:
      'Learn Adobe Photoshop, Illustrator, Canva and design principles to create strong visuals for brands.',
    duration: '4 Months',
    fees: 10000,
    discountedFees: 8000,
    icon: 'GD',
    color: 'from-pink-500 to-rose-500',
    category: 'Creative',
    topics: [
      'Design Principles',
      'Adobe Photoshop',
      'Adobe Illustrator',
      'Canva Pro',
      'Logo Design',
      'Social Media Graphics',
      'Print Design',
      'Brand Identity',
    ],
    roadmap: [
      { week: 'Month 1', title: 'Design Fundamentals', desc: 'Color, typography, and composition' },
      { week: 'Month 2', title: 'Adobe Photoshop', desc: 'Photo editing and manipulation' },
      { week: 'Month 3', title: 'Adobe Illustrator', desc: 'Vector design and logo creation' },
      { week: 'Month 4', title: 'Brand Projects', desc: 'Real client projects and portfolio building' },
    ],
    badge: 'Creative',
    popular: false,
  },
  {
    slug: 'video-editing',
    title: 'Video Editing',
    fullName: 'Professional Video Editing & Production',
    description:
      'Master Adobe Premiere Pro, After Effects and CapCut to create cinematic videos for YouTube, Reels and brands.',
    duration: '3 Months',
    fees: 9000,
    discountedFees: 7500,
    icon: 'VE',
    color: 'from-green-500 to-teal-500',
    category: 'Creative',
    topics: [
      'Premiere Pro',
      'After Effects',
      'CapCut',
      'Color Grading',
      'Motion Graphics',
      'Audio Editing',
      'YouTube Optimization',
      'Reel Creation',
    ],
    roadmap: [
      { week: 'Week 1-2', title: 'Video Editing Basics', desc: 'Timeline, cuts, and transitions' },
      { week: 'Week 3-4', title: 'Adobe Premiere Pro', desc: 'Professional video editing workflows' },
      { week: 'Week 5-6', title: 'After Effects', desc: 'Motion graphics and VFX basics' },
      { week: 'Week 7-8', title: 'Color & Audio', desc: 'Grading, mixing, and mastering' },
      { week: 'Week 9-12', title: 'YouTube & Reels Projects', desc: 'Real content creation projects' },
    ],
    badge: 'Trending',
    popular: false,
  },
  {
    slug: 'ai-tools',
    title: 'Learn AI Tools',
    fullName: 'AI Tools Mastery for Professionals',
    description:
      'Learn ChatGPT, image tools, Canva AI, automation tools and prompt engineering to supercharge productivity.',
    duration: '2 Months',
    fees: 6000,
    discountedFees: 5000,
    icon: 'AI',
    color: 'from-cyan-500 to-blue-600',
    category: 'AI & Tech',
    topics: [
      'ChatGPT Mastery',
      'Prompt Engineering',
      'AI Image Tools',
      'Canva AI',
      'AI Writing Tools',
      'Automation (Zapier)',
      'AI for Business',
      'Future of AI',
    ],
    roadmap: [
      { week: 'Week 1-2', title: 'AI Fundamentals', desc: 'What AI is and which tools matter' },
      { week: 'Week 3-4', title: 'ChatGPT & Prompting', desc: 'Prompt engineering and productivity workflows' },
      { week: 'Week 5-6', title: 'AI Image & Design Tools', desc: 'Creative and design-focused AI tools' },
      { week: 'Week 7-8', title: 'AI Automation & Business', desc: 'Workflows, productivity, and careers' },
    ],
    badge: 'Future Ready',
    popular: true,
  },
];

export const INSTITUTE_INFO = {
  name: 'Balaji Computer Classes',
  tagline: 'Shaping Digital Futures',
  shortName: 'BCC',
  founded: '2018',
  totalStudents: '2000+',
  placementRate: '85%',
  courses: '10+',
  phone: '+91 98765 43210',
  whatsapp: '919876543210',
  email: 'info@balajicomputerclasses.in',
  address: 'Main Market Road, Near Bus Stand, Rajasthan 302001',
  timings: 'Mon-Sat: 9 AM - 7 PM',
  socialMedia: {
    instagram: 'https://instagram.com/balajicomputerclasses',
    youtube: 'https://youtube.com/@balajicomputerclasses',
    facebook: 'https://facebook.com/balajicomputerclasses',
  },
};

export const TESTIMONIALS = [
  {
    name: 'Priya Sharma',
    course: 'Web Development',
    text: 'Balaji Computer Classes ne meri zindagi badal di. Web development seekhne ke baad mujhe ek achhi company mein job mili.',
    rating: 5,
    placed: 'Placed at TCS Mumbai',
    avatar: 'PS',
  },
  {
    name: 'Rahul Verma',
    course: 'Digital Marketing',
    text: 'Yahan practical knowledge bahut zyada mili. Ab main apna freelancing business confidently chala raha hoon.',
    rating: 5,
    placed: 'Freelancer earning Rs. 40K/month',
    avatar: 'RV',
  },
  {
    name: 'Anjali Meena',
    course: 'RS-CIT',
    text: 'RS-CIT exam first attempt mein clear hua. Teachers ne bahut achhe se samjhaya aur fees bhi reasonable thi.',
    rating: 5,
    placed: 'Govt. Job Preparation',
    avatar: 'AM',
  },
  {
    name: 'Deepak Joshi',
    course: 'Graphic Designing',
    text: 'Graphic designing course ke baad social media ke liye paid projects milne lage. Institute ka environment bahut positive hai.',
    rating: 4,
    placed: 'Working at Local Agency',
    avatar: 'DJ',
  },
];
